#!/usr/bin/env python3
"""
Build js/data/paints.js (paint names, ranges and colours for the paint picker) from
Arcturus5404/miniature-paints (MIT licence).

Usage:
  git clone --depth 1 https://github.com/Arcturus5404/miniature-paints miniature-paints
  python3 tools/build_paints.py miniature-paints
"""
import os, re, sys, json, subprocess

SRC = sys.argv[1] if len(sys.argv) > 1 else "miniature-paints"
OUT = os.path.join(os.path.dirname(__file__), "..", "js", "data", "paints.js")

# file -> brand name shown in the app, and which ranges to keep (None = all)
BRANDS = [
  ("Citadel_Colour", "Citadel", None),
  ("Army_Painter", "Army Painter", None),
  ("Vallejo", "Vallejo", re.compile(r"game|model color|xpress|mecha|primer|wash|pigment|metal", re.I)),
  ("Scale75", "Scale75", None),
  ("AK", "AK Interactive", re.compile(r"3rd gen|quick gen|wargame|game|primer|wash|enamel", re.I)),
  ("Monument", "Pro Acryl", None),
  ("Reaper", "Reaper", None),
  ("P3", "P3", None),
  ("GreenStuffWorld", "Green Stuff World", None),
  ("Duncan", "Two Thin Coats", None),
  ("TurboDork", "Turbo Dork", None),
]

def rows(path):
    lines = open(path, encoding="utf-8").read().splitlines()
    head = None
    for ln in lines:
        if not ln.startswith("|"): continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if head is None:
            if "Name" in cells: head = cells
            continue
        if set(cells[0]) <= set("-: "): continue
        yield dict(zip(head, cells))

out_brands, paints, seen = [], [], set()
for fn, brand, keep in BRANDS:
    p = os.path.join(SRC, "paints", fn + ".md")
    if not os.path.exists(p): print("missing", p, file=sys.stderr); continue
    bi = len(out_brands); out_brands.append(brand); n = 0
    for r in rows(p):
        name = (r.get("Name") or "").strip()
        rng = (r.get("Set") or "").strip()
        m = re.search(r"#([0-9A-Fa-f]{6})", r.get("Hex") or "")
        if not name or not m: continue
        if keep and not keep.search(rng): continue
        key = (bi, name.lower(), rng.lower())
        if key in seen: continue
        seen.add(key)
        paints.append([bi, name, rng, "#" + m.group(1).lower()]); n += 1
    print(f"{brand:18} {n}", file=sys.stderr)

try: commit = subprocess.check_output(["git", "-C", SRC, "log", "-1", "--format=%h %cs"], text=True).strip()
except Exception: commit = ""
data = {"source": "Arcturus5404/miniature-paints", "commit": commit, "license": "MIT", "brands": out_brands, "paints": paints}
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("/* Generated by tools/build_paints.py from Arcturus5404/miniature-paints " + commit + " (MIT). Do not edit by hand. */\n")
    fh.write("window.LEDGER_PAINTS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes", file=sys.stderr)
